version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - springboot-mongo-network


  sb-user-business:
    image: sb-user-business
    build: 
      context: ./sb-user-business
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7072:7072"
    networks:
      - springboot-mongo-network

  sb-blog-business:
    image: sb-blog-business
    build: 
      context: ./sb-blog-business
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7071:7071"
    networks:
      - springboot-mongo-network

  sb-blog-info:
    image: sb-blog-info
    build: 
      context: ./sb-blog-info
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7070:7070"
    networks:
      - springboot-mongo-network

  
volumes:
  mongo-data:

networks:
  springboot-mongo-network:
