# MongoDB Configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive-db
      database: reactive-db

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    reactor.netty: INFO
    org.springframework.web: INFO

# Review Service Configuration
review:
  service:
    url: http://localhost:8081 