openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0

paths:
  /blogs/v1/:
    get:
      summary: Retrieve all blogs
      operationId: getBlogs
      responses:
        default:
          $ref: '#/components/responses/HttpErrorResponse'
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlogReq'
    post:
      summary: Add a new user
      operationId: addBlog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogReq'
      responses:
        default:
          $ref: '#/components/responses/HttpErrorResponse'
        '201':
          description: User added successfully
  /blogs/v1/search:
    get:
      tags:
        - Users
      summary: Search blogs
      description: It will provide search capability on users.
      operationId: searchBlogs
      parameters:
        - name: query
          in: query
          description: Search user on basis on RSQL expression
          required: false
          explode: true
          schema:
            type: string
        - name: sortBy
          in: query
          required: false
          schema:
            type: string
        - name: size
          in: query
          required: true
          schema:
            type: integer
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: sortDir
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request was successful
          content:
            application/json:
              schema:
                type: object
        default:
          $ref: '#/components/responses/HttpErrorResponse'

  /blogs/v1/{userId}:
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
    get:
      summary: Retrieve a user by ID
      operationId: getBlogById
      responses:
        default:
          $ref: '#/components/responses/HttpErrorResponse'
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogReq'
        '404':
          description: User not found
    put:
      summary: Update a user by ID
      operationId: updateUserById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogReq'
      responses:
        default:
          $ref: '#/components/responses/HttpErrorResponse'
        '200':
          description: User updated successfully
        '404':
          description: User not found
    delete:
      summary: Delete a user by ID
      operationId: deleteUserById
      responses:
        default:
          $ref: '#/components/responses/HttpErrorResponse'
        '204':
          description: User deleted successfully
        '404':
          description: User not found

components:
  schemas:

    # User entity
    BlogReq:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
    APIError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

  responses:
    HttpErrorResponse:
      description: The request has failed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'